### ISSUE TITLE
Pasta fantasma

### ISSUE THREAD

**Issue by robertosouza5991** [mat-esp-uerj/capstone-camila-dyellen-maisum#1]
Não sei como remover esta pasta fantasma, vazia, que surgiu no repositório.
O resto esta OK

**Comment by victortxa** [comment]
@robertosouza5991 @camilareveles @dyyhqueiroz  o issue é para ser aberto aqui: https://github.com/leouieda/matematica-especial/issues e não no próprio repositório da tarefa...

**Comment by robertosouza5991** [comment]
Este é um issue para o grupo, e não o de entrega do trabalho ;-).

Em 15/01/2016 11:13, victortxa escreveu:

**Comment by victortxa** [comment]
:+1:
