### ISSUE TITLE
capstone-camila-dyellen-maisum

### ISSUE THREAD

**Issue by dyyhqueiroz** [mat-esp-uerj/capstone-camila-dyellen-maisum#2]
turma 2

**Comment by victortxa** [comment]
@dyyhqueiroz  o issue deve ser aberto aqui: https://github.com/leouieda/matematica-especial e não no próprio repositório com a prática!!! Olhe na página principal da disciplina ou peça ajuda para alguém o mais rápido.

**Comment by dyyhqueiroz** [comment]
Eu abri uma issue na sexta-feira à noite. Ela não está aparecendo?

Att,
Dyellen Queiroz
Em 18 de jan de 2016 12:12 PM, "victortxa" notifications@github.com
escreveu:

**Comment by victortxa** [comment]
@dyyhqueiroz Não sei. Basta você verificar na página.

**Comment by dyyhqueiroz** [comment]
Conferi. Ela foi criada ;)
Em 18 de jan de 2016 12:17 PM, "victortxa" notifications@github.com
escreveu:

**Comment by victortxa** [comment]
:+1:
